modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/ServerCountryFlags/issues"

[[mods]]
modId = "servercountryflags"
version = "${version}"
logoFile="icon.png"
displayName = "Server Country Flags"
authors = "Khajiitos"
displayURL="https://github.com/Khajiitos/ServerCountryFlags"
description = '''Shows the flag of where a server is located.'''

[[dependencies.servercountryflags]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.servercountryflags]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
