# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.10
minecraft_version_group=1.21.10

mod_id=servercountryflags
mod_version=1.10.4

fabric_loader_version=0.17.3
fabric_version=0.136.0+1.21.10
fabric_minecraft_version_range=>=1.21.9 <1.22

# 1.21.5 versions
server_browser_artifact_id_forge=6412545
server_browser_artifact_id_fabric=6412548
server_browser_artifact_id_neoforged=6412556

forge_version=60.0.11
forge_version_range=[59,)
forge_loader_version_range=[59,)
forge_minecraft_version_range=[1.21.9,1.22)

neo_version=21.10.32-beta
neo_version_range=[21,)
neo_loader_version_range=[1,)

cloth_config_version=20.0.148
modmenu_version=16.0.0-rc.1
raknetify_version=1.21-0.1.0+alpha.5.124